# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('departure', models.TimeField()),
                ('arrival', models.TimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway.Destination')),
                ('train_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_0', to='subway.Train')),
                ('train_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_1', to='subway.Train')),
                ('train_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_2', to='subway.Train')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='trains',
            field=models.ManyToManyField(to='subway.Train'),
        ),
    ]
