# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='train_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_1', to='subway.Train'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='train_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_2', to='subway.Train'),
        ),
    ]
